### ISSUE TITLE
添加 MIRAI 作为静态检查工具

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#36]
> MIRAI is an abstract interpreter for the [Rust](https://www.rust-lang.org/) compiler's [mid-level intermediate representation](https://github.com/rust-lang/rfcs/blob/master/text/1211-mir.md) (MIR). It is intended to become a widely used static analysis tool for Rust.

MIRAI 是 Rust 生态中可能最成熟的静态检查工具，尽管它的社区知名度并不高。

它的首次提交在 2018 年，曾是 facebook 的一个[实验项目](https://github.com/facebookexperimental/MIRAI)，2024 年 8 月转移到了新的组织： https://github.com/endorlabs/MIRAI

在 endorlabs 网页，有一个流程介绍：https://docs.endorlabs.com/scan-with-endorlabs/language-scanning/rust/

但更详细的是 MIRAI 自己的文档：https://github.com/endorlabs/MIRAI/tree/main/documentation

暂时还没有仔细研究它的功能，尽管我知道它有一段时间了。

目前看到的一些限制：
* 目前 Rust 工具链固定到 nightly-2023-12-30，虽然有些旧，但从历史提交看，它更新工具链是频繁且稳进的 
<details><summary>Toolchain History</summary>
<p>

![截图_20240828133906](https://github.com/user-attachments/assets/8b81a2da-bb94-4597-ae2a-cea06a7bc619)

</p>
</details> 

* 必须成功构建 (cargo build) 才能静态分析

**Comment by zjp-CN** [comment]
在 [CI](https://github.com/os-checker/os-checker/actions/runs/10858833087) 中随便测试两个小仓库，遇到服务器无响应的问题

```rust
X run in 44m55s (ID 30137342751)
  ✓ Set up job
  ✓ Run actions/checkout@v4
  ✓ Run webfactory/ssh-agent@v0.9.0
  ✓ Download repos-ui.json
  ✓ Set Up Github Environment Variables
  ✓ Run dtolnay/rust-toolchain@master
  - Run sccache-cache
  ✓ Restore Cargo Cache
  ✓ Install os-checker
  ✓ Display Repos Layouts
  ✓ Prepare toolchain environment needed from all repos and checkers
  X Run All Checkers
  X Commit And Push To database repo
  X Save Cargo Cache
  X Post Run webfactory/ssh-agent@v0.9.0
  X Post Run actions/checkout@v4

ANNOTATIONS
X The hosted runner: GitHub Actions 8 lost communication with the server. 
Anything in your workflow that terminates the runner process, starves it for CPU/Memory, 
or blocks its network access can cause this error.
```

mirai 文档中描述了一个[运行条件](https://docs.endorlabs.com/scan-with-endorlabs/language-scanning/rust/#install-software-prerequisites)

> Make sure that you have a minimum system requirement specification of an 8-core processor with 32 GB RAMs.

Github Action 的服务器规格肯定低于这个，所以如果 mirai 实在无法得到结果，可能需要暂时放弃它。

**Comment by zjp-CN** [comment]
一个结果示例：

![截图_20240914215921](https://github.com/user-attachments/assets/db407051-d175-409b-a724-3967ec67cba4)

**Comment by zjp-CN** [comment]
检查所有仓库时再次遇到空间耗尽

```rust
  X Run All Checkers
  X Commit And Push To database repo
  X Post Run webfactory/ssh-agent@v0.9.0
  X Post Run actions/checkout@v4

ANNOTATIONS
X System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240925-000514-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240925-000514-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240925-000514-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
run: .github#1
```

**Comment by zjp-CN** [comment]
已初步完成。虽然目前只在 x86_64-unknown-linux-gnu 上检查代码，如果以后需要在其他 target 上检查，则新开 issue。
