### ISSUE TITLE
CI: 一次性分析所有 kerns-crates 导致磁盘空间耗尽

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#54]
```rust
X Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240903-230614-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240903-230614-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240903-230614-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
run: .github#1

! You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 82 MB
run: .github#30
```

解决方式：增加一个 `--batch` 参数，表示每次运行 os-checker 最多运行的仓库检查数量，并且每个 batch 完成之后，把这些仓库从磁盘上清除，但保留运行结果。我的想法是，如果指定了 --batch，那么首先把合并后的配置切分成小配置写入到文件，然后通过子进程，调用 `mkdir batch-n-repos && cd batch-n-repos && os-checker --config ../batch/n.json`，然后这些保存结果到 `../output/batch-n.json`，删除 `batch-n-repos`，以此运行到最后那个 batch。最后把结果拼接成一个大的 JSON（或者不拼接？因此 jq 支持读入多个 json 来处理）。

**Comment by zjp-CN** [comment]
将 os-checker CLI 参数拆成 setup 和 run 子命令，并添加 batch 子命令，从而减少了指定参数的复杂度，让使用的方式更简单。

与此 issue 最相关的是把目标仓库下载到单独的目录，在每次分析完之后删除这个目录，那么就解决了磁盘空间耗尽的问题。

 `os-checker batch --size 8 ...` 命令在带有一定缓存的 Github Action 上需要半小时分析完 89 个仓库（由于有些仓库在 setup 阶段存在一些小问题，我把它们暂时剔除了）。

https://github.com/os-checker/os-checker/actions/runs/10704085110/job/29676186208

![截图_20240905074408](https://github.com/user-attachments/assets/737b79c4-4409-4e27-a831-d518b47ef736)
